import type { Preset, LayerParams } from './types';

// Helper to create a new layer with safe defaults
export const createDefaultLayer = (type: 'binaural' | 'isochronic' | 'monaural'): LayerParams => {
  const id = crypto.randomUUID();

  switch (type) {
    case 'binaural':
      return {
        id,
        type: 'binaural',
        carrierLeft: 200,
        carrierRight: 210,
        beatHz: 10,
        waveform: 'sine',
        gainDb: -18, // Default gain for new layers (lower to prevent distortion)
        pan: 0,
        env: { attack: 0.1, decay: 0.1, sustain: 0.8, release: 0.5 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      };
    case 'isochronic':
      return {
        id,
        type: 'isochronic',
        carrier: 200,
        beatHz: 10,
        waveform: 'sine',
        gainDb: -18, // Default gain for new layers (lower to prevent distortion)
        pan: 0,
        env: { attack: 0.05, decay: 0.05, sustain: 0.9, release: 0.3 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      };
    case 'monaural':
      return {
        id,
        type: 'monaural',
        carrier: 200,
        beatHz: 10,
        waveform: 'sine',
        gainDb: -18, // Default gain for new layers (lower to prevent distortion)
        pan: 0,
        env: { attack: 0.1, decay: 0.1, sustain: 0.8, release: 0.5 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      };
  }
};

// Built-in presets
export const builtInPresets: Preset[] = [
  {
    id: 'productivity',
    name: 'Productivity',
    description: 'Multi-layered productivity preset with optimized LFO rates for sustained focus and cognitive enhancement',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 200,
        carrierRight: 210,
        beatHz: 10,
        waveform: 'sine',
        gainDb: -16,
        pan: 0,
        env: { attack: 0.10, decay: 0.10, sustain: 0.8, release: 0.5 },
        lfo: { enabled: true, rateHz: 0.01, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 180,
        beatHz: 14,
        waveform: 'sine',
        gainDb: -12,
        pan: 0,
        env: { attack: 0.5, decay: 0.5, sustain: 0.9, release: 0.3 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'monaural',
        carrier: 210,
        beatHz: 18,
        waveform: 'sine',
        gainDb: -20,
        pan: 0,
        env: { attack: 0.10, decay: 0.10, sustain: 0.8, release: 0.5 },
        lfo: { enabled: true, rateHz: 0.5, depth: 10, target: 'gain' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 300,
        carrierRight: 340,
        beatHz: 40,
        waveform: 'sine',
        gainDb: -30,
        pan: 0,
        env: { attack: 0.10, decay: 0.10, sustain: 0.8, release: 0.5 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 120,
        carrierRight: 130,
        beatHz: 10,
        waveform: 'sine',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.10, decay: 0.10, sustain: 0.8, release: 0.5 },
        lfo: { enabled: true, rateHz: 0.01, depth: 25, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 150,
        carrierRight: 157.5,
        beatHz: 7.5,
        waveform: 'sine',
        gainDb: -22,
        pan: 0,
        env: { attack: 0.10, decay: 0.10, sustain: 0.8, release: 0.5 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'meditative',
    name: 'Meditative',
    description: 'Deep trance state with very low frequencies and slow LFO modulation for profound relaxation and meditation',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 21,
        carrierRight: 30,
        beatHz: 9,
        waveform: 'sine',
        gainDb: -14,
        pan: 0,
        env: { attack: 1.0, decay: 0.5, sustain: 0.95, release: 2.0 },
        lfo: { enabled: true, rateHz: 0.01, depth: 15, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 30,
        carrierRight: 33,
        beatHz: 3,
        waveform: 'sine',
        gainDb: -10,
        pan: 0,
        env: { attack: 0.8, decay: 0.4, sustain: 0.9, release: 1.5 },
        lfo: { enabled: true, rateHz: 0.03, depth: 12, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 50,
        carrierRight: 56,
        beatHz: 6,
        waveform: 'sine',
        gainDb: -16,
        pan: 0,
        env: { attack: 0.5, decay: 0.3, sustain: 0.95, release: 1.0 },
        lfo: { enabled: true, rateHz: 0.03, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'monaural',
        carrier: 60,
        beatHz: 0.1,
        waveform: 'sine',
        gainDb: -24,
        pan: 0,
        env: { attack: 1.2, decay: 0.6, sustain: 0.9, release: 2.5 },
        lfo: { enabled: true, rateHz: 0.01, depth: 20, target: 'gain' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 432,
        beatHz: 0.1,
        waveform: 'sine',
        gainDb: -38,
        pan: 0,
        env: { attack: 3.45, decay: 0.3, sustain: 0.9, release: 1.2 },
        lfo: { enabled: true, rateHz: 0.03, depth: 30, target: 'gain' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 256,
        beatHz: 0.2,
        waveform: 'sine',
        gainDb: -30,
        pan: 0,
        env: { attack: 3.72, decay: 0.05, sustain: 0.9, release: 1.52 },
        lfo: { enabled: true, rateHz: 0.01, depth: 20, target: 'gain' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 288,
        beatHz: 0.1,
        waveform: 'sine',
        gainDb: -32,
        pan: 0,
        env: { attack: 4, decay: 1, sustain: 0.46, release: 1.5 },
        lfo: { enabled: true, rateHz: 0.06, depth: 30, target: 'gain' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'deep-focus-flow',
    name: 'Deep Focus Flow',
    description: '12-15 Hz SMR range for sustained attention and reduced mind wandering',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 200,
        beatHz: 13.5,
        waveform: 'square',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.1, decay: 0.1, sustain: 0.9, release: 0.3 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 200,
        carrierRight: 213,
        beatHz: 13,
        waveform: 'sine',
        gainDb: -26,
        pan: 0,
        env: { attack: 0.2, decay: 0.1, sustain: 0.8, release: 0.5 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'sleep-induction-drift',
    name: 'Sleep Induction Drift',
    description: 'Delta 0.5-4 Hz with theta pre-ramp for deep sleep onset',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 150,
        carrierRight: 152,
        beatHz: 2,
        waveform: 'sine',
        gainDb: -21,
        pan: 0,
        env: { attack: 0.5, decay: 0.3, sustain: 0.95, release: 2.0 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 100,
        beatHz: 0.5,
        waveform: 'sine',
        gainDb: -26,
        pan: 0,
        env: { attack: 0.3, decay: 0.2, sustain: 0.9, release: 1.5 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'creative-flow-state',
    name: 'Creative Flow State',
    description: 'Theta 6-7 Hz coupled with gamma 40 Hz for insight and creativity',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 200,
        carrierRight: 206,
        beatHz: 6,
        waveform: 'sine',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.2, decay: 0.1, sustain: 0.8, release: 0.8 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 200,
        beatHz: 40,
        waveform: 'square',
        gainDb: -26,
        pan: 0,
        env: { attack: 0.05, decay: 0.05, sustain: 0.7, release: 0.3 },
        lfo: { enabled: true, rateHz: 0.2, depth: 15, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'stress-relief-meditation',
    name: 'Stress Relief Meditation',
    description: 'Alpha 8-10 Hz for calm alertness and reduced anxiety',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 200,
        beatHz: 9,
        waveform: 'sine',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.3, decay: 0.2, sustain: 0.9, release: 0.8 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 200,
        carrierRight: 209,
        beatHz: 9,
        waveform: 'sine',
        gainDb: -21,
        pan: 0,
        env: { attack: 0.2, decay: 0.1, sustain: 0.8, release: 0.6 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'morning-gamma-boost',
    name: 'Morning Gamma Boost',
    description: 'Gamma 40 Hz for cognitive activation and morning energy',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 200,
        beatHz: 40,
        waveform: 'square',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.05, decay: 0.05, sustain: 0.8, release: 0.2 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'monaural',
        carrier: 400,
        beatHz: 40,
        waveform: 'sine',
        gainDb: -21,
        pan: 0,
        env: { attack: 0.1, decay: 0.05, sustain: 0.8, release: 0.3 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'power-nap-reset',
    name: 'Power Nap Reset',
    description: 'Theta 6 Hz to Alpha 10 Hz for restorative short naps',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 220,
        carrierRight: 226,
        beatHz: 6,
        waveform: 'sine',
        gainDb: -21,
        pan: 0,
        env: { attack: 0.3, decay: 0.2, sustain: 0.9, release: 1.0 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 200,
        beatHz: 10,
        waveform: 'sine',
        gainDb: -26,
        pan: 0,
        env: { attack: 0.1, decay: 0.1, sustain: 0.8, release: 0.5 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'zen-stillness',
    name: 'Zen Stillness',
    description: 'Ultra-slow 0.1 Hz isochronic pulse with 5 Hz theta binaural for deep stillness and meditation',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 200,
        beatHz: 0.1,
        waveform: 'sine',
        gainDb: -14,
        pan: 0,
        env: { attack: 0.5, decay: 0.3, sustain: 0.95, release: 1.5 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 200,
        carrierRight: 205,
        beatHz: 5,
        waveform: 'sine',
        gainDb: -20,
        pan: 0,
        env: { attack: 0.3, decay: 0.2, sustain: 0.9, release: 1.0 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'pre-workout-ignite',
    name: 'Pre-Workout Ignite',
    description: 'High beta 18-20 Hz for physical readiness and energizing prep',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 200,
        beatHz: 19,
        waveform: 'square',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.05, decay: 0.05, sustain: 0.8, release: 0.2 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'monaural',
        carrier: 300,
        beatHz: 19,
        waveform: 'sine',
        gainDb: -21,
        pan: 0,
        env: { attack: 0.1, decay: 0.05, sustain: 0.8, release: 0.3 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'lucid-dream-gateway',
    name: 'Lucid Dream Gateway',
    description: 'Theta 7 Hz to Delta 3 Hz cycling for hypnagogic exploration',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 180,
        carrierRight: 187,
        beatHz: 7,
        waveform: 'sine',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.3, decay: 0.2, sustain: 0.9, release: 1.0 },
        lfo: { enabled: false, rateHz: 0.1, depth: 10, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 180,
        carrierRight: 183,
        beatHz: 3,
        waveform: 'sine',
        gainDb: -26,
        pan: 0,
        env: { attack: 0.5, decay: 0.3, sustain: 0.95, release: 1.5 },
        lfo: { enabled: true, rateHz: 0.15, depth: 12, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'mind-cleanse',
    name: 'Mind Cleanse',
    description: 'Alpha sweep 8-12 Hz cycling for stress reset and decompression',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 200,
        beatHz: 10,
        waveform: 'sine',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.2, decay: 0.1, sustain: 0.8, release: 0.5 },
        lfo: { enabled: true, rateHz: 0.2, depth: 20, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 200,
        carrierRight: 210,
        beatHz: 10,
        waveform: 'sine',
        gainDb: -26,
        pan: 0,
        env: { attack: 0.2, decay: 0.1, sustain: 0.8, release: 0.6 },
        lfo: { enabled: true, rateHz: 0.2, depth: 15, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'ocean-waves',
    name: 'Ocean Waves',
    description: 'Gentle LFO-modulated binaural waves mimicking ocean rhythms',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 180,
        carrierRight: 188,
        beatHz: 8,
        waveform: 'sine',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.8, decay: 0.4, sustain: 0.9, release: 1.2 },
        lfo: { enabled: true, rateHz: 0.08, depth: 25, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 220,
        carrierRight: 225,
        beatHz: 4,
        waveform: 'sine',
        gainDb: -24,
        pan: 0,
        env: { attack: 1.0, decay: 0.5, sustain: 0.95, release: 1.5 },
        lfo: { enabled: true, rateHz: 0.12, depth: 18, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'cosmic-drift',
    name: 'Cosmic Drift',
    description: 'Ethereal LFO-modulated frequencies creating space-like ambience',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 200,
        carrierRight: 210,
        beatHz: 6,
        waveform: 'sine',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.5, decay: 0.3, sustain: 0.9, release: 1.0 },
        lfo: { enabled: true, rateHz: 0.15, depth: 30, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 300,
        beatHz: 12,
        waveform: 'triangle',
        gainDb: -21,
        pan: 0,
        env: { attack: 0.3, decay: 0.2, sustain: 0.8, release: 0.8 },
        lfo: { enabled: true, rateHz: 0.1, depth: 20, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'monaural',
        carrier: 400,
        beatHz: 24,
        waveform: 'sine',
        gainDb: -26,
        pan: 0,
        env: { attack: 0.2, decay: 0.1, sustain: 0.7, release: 0.6 },
        lfo: { enabled: true, rateHz: 0.2, depth: 15, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'harmonic-resonance',
    name: 'Harmonic Resonance',
    description: 'Musical harmonic series with LFO creating evolving overtones',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 200,
        carrierRight: 220,
        beatHz: 20,
        waveform: 'sine',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.2, decay: 0.1, sustain: 0.8, release: 0.5 },
        lfo: { enabled: true, rateHz: 0.18, depth: 22, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 300,
        carrierRight: 330,
        beatHz: 30,
        waveform: 'sine',
        gainDb: -21,
        pan: 0,
        env: { attack: 0.15, decay: 0.08, sustain: 0.75, release: 0.4 },
        lfo: { enabled: true, rateHz: 0.22, depth: 18, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 400,
        carrierRight: 440,
        beatHz: 40,
        waveform: 'sine',
        gainDb: -24,
        pan: 0,
        env: { attack: 0.1, decay: 0.05, sustain: 0.7, release: 0.3 },
        lfo: { enabled: true, rateHz: 0.25, depth: 15, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'aurora-borealis',
    name: 'Aurora Borealis',
    description: 'Dancing LFO patterns mimicking the northern lights',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 180,
        carrierRight: 195,
        beatHz: 15,
        waveform: 'sine',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.4, decay: 0.2, sustain: 0.85, release: 0.8 },
        lfo: { enabled: true, rateHz: 0.3, depth: 28, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 190,
        // other carrier is 250, so the binaural is 190 and 250
        beatHz: 0.1,
        waveform: 'triangle',
        gainDb: -22,
        pan: 0,
        env: { attack: 0.6, decay: 0.3, sustain: 0.9, release: 1.0 },
        lfo: { enabled: true, rateHz: 0.25, depth: 20, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'monaural',
        carrier: 350,
        beatHz: 35,
        waveform: 'sine',
        gainDb: -26,
        pan: 0,
        env: { attack: 0.3, decay: 0.15, sustain: 0.8, release: 0.7 },
        lfo: { enabled: true, rateHz: 0.35, depth: 12, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'neural-symphony',
    name: 'Neural Symphony',
    description: 'Complex LFO orchestration creating musical brainwave patterns',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 200,
        carrierRight: 206,
        beatHz: 6,
        waveform: 'sine',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.3, decay: 0.15, sustain: 0.85, release: 0.7 },
        lfo: { enabled: true, rateHz: 0.12, depth: 25, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 240,
        carrierRight: 252,
        beatHz: 12,
        waveform: 'sine',
        gainDb: -21,
        pan: 0,
        env: { attack: 0.2, decay: 0.1, sustain: 0.8, release: 0.5 },
        lfo: { enabled: true, rateHz: 0.15, depth: 20, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 320,
        beatHz: 18,
        waveform: 'triangle',
        gainDb: -24,
        pan: 0,
        env: { attack: 0.15, decay: 0.08, sustain: 0.75, release: 0.4 },
        lfo: { enabled: true, rateHz: 0.18, depth: 18, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'monaural',
        carrier: 400,
        beatHz: 24,
        waveform: 'sine',
        gainDb: -27,
        pan: 0,
        env: { attack: 0.1, decay: 0.05, sustain: 0.7, release: 0.3 },
        lfo: { enabled: true, rateHz: 0.2, depth: 15, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'quantum-flow',
    name: 'Quantum Flow',
    description: 'Rapid LFO modulation creating quantum-like frequency fluctuations',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 220,
        carrierRight: 235,
        beatHz: 15,
        waveform: 'sine',
        gainDb: -18,
        pan: 0,
        env: { attack: 0.1, decay: 0.05, sustain: 0.8, release: 0.3 },
        lfo: { enabled: true, rateHz: 0.4, depth: 30, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 280,
        beatHz: 21,
        waveform: 'square',
        gainDb: -21,
        pan: 0,
        env: { attack: 0.08, decay: 0.04, sustain: 0.75, release: 0.25 },
        lfo: { enabled: true, rateHz: 0.35, depth: 25, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 360,
        carrierRight: 384,
        beatHz: 24,
        waveform: 'sine',
        gainDb: -24,
        pan: 0,
        env: { attack: 0.06, decay: 0.03, sustain: 0.7, release: 0.2 },
        lfo: { enabled: true, rateHz: 0.45, depth: 20, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'celestial-harmony',
    name: 'Celestial Harmony',
    description: 'Slow, majestic LFO patterns creating cosmic musical intervals',
    layers: [
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 200,
        carrierRight: 220,
        beatHz: 20,
        waveform: 'sine',
        gainDb: -18,
        pan: 0,
        env: { attack: 1.0, decay: 0.5, sustain: 0.95, release: 2.0 },
        lfo: { enabled: true, rateHz: 0.05, depth: 35, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'binaural',
        carrierLeft: 300,
        carrierRight: 330,
        beatHz: 30,
        waveform: 'sine',
        gainDb: -21,
        pan: 0,
        env: { attack: 1.2, decay: 0.6, sustain: 0.9, release: 2.5 },
        lfo: { enabled: true, rateHz: 0.08, depth: 30, target: 'beat' },
        muted: false,
        solo: false,
      },
      {
        id: crypto.randomUUID(),
        type: 'isochronic',
        carrier: 400,
        beatHz: 10,
        waveform: 'triangle',
        gainDb: -24,
        pan: 0,
        env: { attack: 0.8, decay: 0.4, sustain: 0.85, release: 1.5 },
        lfo: { enabled: true, rateHz: 0.06, depth: 25, target: 'beat' },
        muted: false,
        solo: false,
      }
    ]
  },
  {
    id: 'blank',
    name: 'Blank Layer',
    description: 'Start with a single binaural layer',
    layers: [
      createDefaultLayer('binaural')
    ]
  }
];

const builtInPresetIds = new Set(builtInPresets.map(p => p.id));

export const isBuiltInPreset = (id: string): boolean => builtInPresetIds.has(id);

// Helper functions for parameter validation and normalization
export const clampValue = (value: number, min: number, max: number): number => {
  return Math.max(min, Math.min(max, value));
};

export const normalizeLayerParams = (params: Partial<LayerParams>): LayerParams => {
  const defaults = createDefaultLayer('binaural');

  return {
    ...defaults,
    ...params,
    id: params.id || defaults.id,
    beatHz: clampValue(params.beatHz || defaults.beatHz, 0.5, 40),
    gainDb: clampValue(params.gainDb || defaults.gainDb, -48, -18),
    pan: clampValue(params.pan || defaults.pan, -1, 1),
    env: {
      attack: clampValue(params.env?.attack || defaults.env.attack, 0.01, 5),
      decay: clampValue(params.env?.decay || defaults.env.decay, 0.01, 5),
      sustain: clampValue(params.env?.sustain || defaults.env.sustain, 0, 1),
      release: clampValue(params.env?.release || defaults.env.release, 0.01, 10),
    },
    lfo: params.lfo ? {
      enabled: params.lfo.enabled,
      rateHz: clampValue(params.lfo.rateHz, 0.01, 0.5),
      depth: clampValue(params.lfo.depth, 0, 30),
      target: params.lfo.target,
    } : defaults.lfo,
  };
};
